# Generated by Django 4.1 on 2024-04-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_models', '0011_contactperson_can_post_himself'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка на api для загрузки поста')),
                ('code', models.CharField(default='y1V8ZJ4ikDi2QkekrRAkBhIphxT4bRhwJ9hX8NRh5fo89MncqXq9WId3leIbxYKmmOBdjPh7ZnsHO8T53Xnel0Hbi70hGK6S8ecWxlcXHa980LbbrPcvDCtbuItif8B6jGqt0BH6uzzHkRcwhvUhTBoxVwVcN4PCK7bMqAjWHk3rFE5ZqDfW8AgRocS5v1fFLbbkfZG0moMtAovhTbHWG25sUnSbrwI8PrSzRLmrtdg5XbpOkrGC7ldCUgrHUU6eNLM2G7KaOuS3M1B08fcSd20vpabKvytaosSr2fN5lPt8z8hAANqTHegywizkcOY8Tg3CiK2V85DrFXgk5AJS7CiEzTO38484rNX9dyit1hi6cUWckXxnDQVHcqjJo2B3yEZWTOrHromKwHUOHExyNf3HQotlFur2MOdoQwOiBclFmzkmE7SyoenOeS5hyKY5UqdReEb1pIX6rcJNVYEu7HzC5cL7zBitDDNsm9rZHc8ku89n3jEEdTpcTYvBVOa2', editable=False, max_length=100, verbose_name='Код для загрузки постов')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='db_models.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайты',
            },
        ),
    ]
