# Generated by Django 4.1 on 2024-03-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_models', '0008_alter_business_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на группу')),
                ('members_count', models.BigIntegerField(default=0, editable=False, verbose_name='Количество участников')),
                ('group_id', models.CharField(max_length=128, verbose_name='ID группы')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='db_models.business', verbose_name='Бизнес')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
