# Generated by Django 4.1 on 2024-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_vk', '0002_group_community_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='community_token',
        ),
    ]
