# Generated by Django 4.1 on 2024-02-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db_models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Наименование организации"
                    ),
                ),
                ("inn", models.CharField(max_length=128, verbose_name="ИНН")),
                ("ogrn", models.CharField(max_length=128, verbose_name="ОГРН")),
                ("adress", models.CharField(max_length=128, verbose_name="Юр. адрес")),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="ФИО работника"),
                ),
                (
                    "number_phone",
                    models.CharField(max_length=32, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="Почта")),
                (
                    "telegram_user_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Никнейм в телеграмме",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Идентификатор в телеграмме",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работяга",
                "verbose_name_plural": "Работяги",
            },
        ),
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name": "Бизнес", "verbose_name_plural": "Бизнесы"},
        ),
        migrations.AlterField(
            model_name="business",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Наименование бизнеса"),
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        max_length=128, verbose_name="Должность Жоб тайтл"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="ФИО")),
                (
                    "number_phone",
                    models.CharField(max_length=32, verbose_name="Номер телефона"),
                ),
                ("email", models.EmailField(max_length=128, verbose_name="Почта")),
                (
                    "telegram_user_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Никнейм в телеграмме",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Идентификатор в телеграмме",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_person",
                        to="db_models.business",
                        verbose_name="контактное лицо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактное лицо",
                "verbose_name_plural": "Контактные лица",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business",
                to="db_models.organization",
                verbose_name="организация",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="business",
                to="db_models.worker",
                verbose_name="работяга",
            ),
        ),
    ]
