# Generated by Django 4.1 on 2024-02-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("db_models", "0002_organization_worker_alter_business_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="permission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.permission",
            ),
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_person",
                to="db_models.business",
                verbose_name="бизнес",
            ),
        ),
    ]
