# Generated by Django 4.1 on 2024-02-29 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db_models", "0003_contactperson_permission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactperson",
            name="permission",
        ),
        migrations.AlterField(
            model_name="contactperson",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_person",
                to="db_models.business",
                verbose_name="Бизнес",
            ),
        ),
    ]
