# Generated by Django 4.1 on 2024-03-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_alter_organization_adress_alter_organization_inn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'SMM-щик', 'verbose_name_plural': 'SMM-щики'},
        ),
        migrations.AlterField(
            model_name='business',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='db_models.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='business',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='db_models.worker', verbose_name='SMM-щик'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='job_title',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
    ]
