# Generated by Django 4.1 on 2024-03-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_alter_worker_options_alter_business_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_models.business'),
        ),
    ]
