# Generated by Django 4.1 on 2024-03-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0007_business_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='db_models.business', verbose_name='Родительский бизнес'),
        ),
    ]
