# Generated by Django 4.1 on 2024-03-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0008_alter_business_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloaded_files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
    ]
