# Generated by Django 4.1 on 2024-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0010_downloadedfile_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='can_post_himself',
            field=models.BooleanField(default=False, verbose_name='Возможность одобрять свои посты'),
        ),
    ]
