# Generated by Django 4.1 on 2024-02-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soc_telegram", "0002_alter_channel_options_channelofcoordination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="chat_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name_chat",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
