# Generated by Django 4.1 on 2024-02-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soc_telegram", "0003_alter_channel_chat_id_alter_channel_name_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelofcoordination",
            name="chat_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
