# Generated by Django 4.1 on 2024-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_telegram', '0004_alter_channelofcoordination_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='thread_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
