# Generated by Django 4.1 on 2024-03-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_alter_worker_options_alter_business_organization_and_more'),
        ('soc_telegram', '0005_channel_thread_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_chat_id', models.CharField(max_length=256)),
                ('first_message_id', models.CharField(max_length=256)),
                ('media_group_id', models.CharField(max_length=256)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_models.business')),
            ],
        ),
        migrations.CreateModel(
            name='MediaGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=64)),
                ('caption', models.CharField(blank=True, max_length=4096, null=True)),
                ('file_id', models.CharField(max_length=512)),
                ('media_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='soc_telegram.mediagroup')),
            ],
        ),
    ]
