# Generated by Django 4.1 on 2024-03-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_telegram', '0006_mediagroup_mediagroupitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediagroup',
            name='business',
        ),
    ]
