# Generated by Django 4.1 on 2024-03-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_telegram', '0010_remove_calculator_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_calc_channel',
            field=models.BooleanField(default=False),
        ),
    ]
